name: Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull and run Docker image
      run: |
        docker pull nginx
        docker run nginx /bin/bash -c "echo 'Volodymyr Neshchadym'"

